### ISSUE TITLE
Feature Tracking for Initial Release

### ISSUE THREAD

**Issue by wagenet** [wagenet/graphiti-rails#15]
* [x] Register exceptions with Rails https://github.com/wagenet/graphiti-rails/issues/4
* [x] Use either default exception handler or InvalidRequest handler
* [x] Use Graphiti handler only for JSON API by default, with opt-in for other content types

**Comment by wagenet** [comment]
I _think_ we do enough feature wise for an 0.1 release. There's still a little more cleanup to do still.
